# Generated by Django 4.0.6 on 2022-08-08 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finalapp', '0002_work_operating_system'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='work',
            name='operating_system',
        ),
        migrations.AlterField(
            model_name='work',
            name='T_status',
            field=models.CharField(blank=True, choices=[('pending', 'pending'), ('completed', 'completed')], max_length=250, null=True),
        ),
    ]
