# Generated by Django 4.0.6 on 2022-08-13 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finalapp', '0004_alter_work_approval_status_alter_work_t_status'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WORK',
        ),
    ]
