# Generated by Django 4.0.6 on 2022-08-13 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('finalapp', '0005_delete_work'),
    ]

    operations = [
        migrations.CreateModel(
            name='WORK',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('T_name', models.CharField(max_length=250)),
                ('T_id', models.IntegerField()),
                ('T_status', models.CharField(max_length=250)),
                ('Start_tym', models.TimeField()),
                ('End_tym', models.TimeField()),
                ('Create_date', models.DateField()),
                ('Approval_status', models.CharField(max_length=100)),
                ('Assigned_manager', models.CharField(max_length=300)),
                ('T_description', models.CharField(max_length=300)),
            ],
        ),
    ]
