# Generated by Django 4.0.6 on 2022-08-16 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finalapp', '0007_remove_work_id_alter_work_t_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='Approval_status',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
